name: "My Home Automations"
description: "All of my home automations written in TypeScript"
version: "1.0.13"
slug: "automations"
hassio_role: default
init: false

homeassistant_api: true

map:
  - config:rw

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
