name: "My Home Automations"
description: "All of my home automations written in TypeScript"
version: "1.0.2"
slug: "automations"
init: false

environment:
  HASS_HOST: supervisor
  HASS_PORT: 80

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
